"""Canned content: sample schemas, policies, runs. Used by init and runs."""

TEND_TOML = """[workspace]
id       = "{workspace}"
region   = "us"

[targets.staging]
auto_approve_additive = true

[targets.production]
auto_approve_additive = false
require_approvers     = 2

[codegen]
python     = "./gen/tend_types.py"
typescript = "./gen/tend-types.ts"
"""


ACCOUNT_SCHEMA = """entity Account {
  // identity & surrogate key
  id: uuid primary
  external: {
    salesforce_id: string unique
    hubspot_id:    string? unique
  }

  // core fields
  name:   string
  tier:   enum("smb", "mid", "ent")
  region: enum("us", "eu", "apac")
  arr:    money

  // relations
  owned_by: Contact via "primary_owner"
  deals:    collection<Deal>

  // derived fact. Recomputes on any upstream write
  health: computed {
    risk_score() < 0.3 ? "green"
      : risk_score() < 0.6 ? "yellow"
      : "red"
  }
}
"""

CONTACT_SCHEMA = """entity Contact {
  id: uuid primary
  external: {
    salesforce_id: string? unique
    email: string unique
  }

  name:  string
  email: string
  title: string?

  works_at: Account via "employer"
}
"""

DEAL_SCHEMA = """entity Deal {
  id: uuid primary
  external: {
    salesforce_id: string unique
  }

  name:  string
  stage: enum("prospect", "qualified", "proposal", "closed_won", "closed_lost")
  value: money
  close_date: date?

  on:       Account via "deal_account"
  owned_by: Contact via "deal_owner"
}
"""

DEFAULT_POLICY = """policy default_read_guard {
  subject: agent | human
  action:  read
  on:      *

  // deny PII reads from outside the EU region for EU-tagged entities
  deny if subject.region != "eu" and resource.tags contains "pii_eu"

  // allow everything else
  allow
}
"""

EU_PII_POLICY = """policy eu_pii_read {
  version: "v5"
  subject: agent | human
  action:  read
  on:      Contact

  deny if resource.region == "eu"
       and subject.region != "eu"
       and not subject.has_scope("eu_pii")

  allow
}
"""


def sample_runs() -> list[dict]:
    return [
        {
            "id": "run_8f2c",
            "agent": "renewal-risk-v3",
            "status": "failed",
            "started_at": "2026-04-19T22:14:06Z",
            "latency_ms": 1842,
            "error": "tool.refused: write to Deal.notes not declared",
            "reads": ["Account(acct_4102)", "Deal(deal_991a)"],
            "writes_attempted": ["Deal.notes"],
        },
        {
            "id": "run_8f2d",
            "agent": "renewal-risk-v3",
            "status": "ok",
            "started_at": "2026-04-19T22:15:11Z",
            "latency_ms": 1214,
            "reads": ["Account(acct_4103)", "Deal(deal_991b)"],
            "writes": ["Account(acct_4103).health"],
        },
        {
            "id": "run_8f2e",
            "agent": "renewal-risk-v3",
            "status": "ok",
            "started_at": "2026-04-19T22:15:42Z",
            "latency_ms": 984,
            "reads": ["Account(acct_4104)"],
            "writes": [],
        },
    ]


def tail_events(agent: str) -> list[tuple[float, str]]:
    """Delay-in-seconds, line. Streamed by `tend runs tail`."""
    return [
        (0.0, f"[tail] connected, agent={agent}, runtime=2026.04"),
        (0.4, "[tail] waiting for events…"),
        (0.8, "run_8f31  start   reads=[Account(acct_4201)]"),
        (1.3, "run_8f31  tool    call=risk_score() latency=38ms"),
        (1.6, "run_8f31  write   Account(acct_4201).health = \"yellow\""),
        (1.7, "run_8f31  ok      842ms"),
        (2.3, "run_8f32  start   reads=[Account(acct_4202), Deal(deal_552f)]"),
        (3.1, "run_8f32  tool    call=risk_score() latency=41ms"),
        (3.4, "run_8f32  write   Account(acct_4202).health = \"green\""),
        (3.5, "run_8f32  ok      1214ms"),
        (4.2, "run_8f33  start   reads=[Account(acct_4203)]"),
        (4.9, "run_8f33  err     policy.denied: eu_pii_read (subject.region=us)"),
        (5.0, "run_8f33  fail    702ms"),
    ]


PYTHON_STUBS = '''"""Generated by `tend codegen python`. Do not edit."""
from __future__ import annotations
from dataclasses import dataclass
from typing import Literal, Optional

Tier = Literal["smb", "mid", "ent"]
Region = Literal["us", "eu", "apac"]
DealStage = Literal[
    "prospect", "qualified", "proposal", "closed_won", "closed_lost"
]


@dataclass
class Account:
    id: str
    name: str
    tier: Tier
    region: Region
    arr: float
    salesforce_id: str
    hubspot_id: Optional[str] = None
    health: Optional[Literal["green", "yellow", "red"]] = None


@dataclass
class Contact:
    id: str
    name: str
    email: str
    title: Optional[str] = None
    salesforce_id: Optional[str] = None


@dataclass
class Deal:
    id: str
    name: str
    stage: DealStage
    value: float
    salesforce_id: str
    close_date: Optional[str] = None
'''


TYPESCRIPT_STUBS = """// Generated by `tend codegen typescript`. Do not edit.

export type Tier = "smb" | "mid" | "ent";
export type Region = "us" | "eu" | "apac";
export type DealStage =
  | "prospect"
  | "qualified"
  | "proposal"
  | "closed_won"
  | "closed_lost";

export interface Account {
  id: string;
  name: string;
  tier: Tier;
  region: Region;
  arr: number;
  salesforce_id: string;
  hubspot_id?: string;
  health?: "green" | "yellow" | "red";
}

export interface Contact {
  id: string;
  name: string;
  email: string;
  title?: string;
  salesforce_id?: string;
}

export interface Deal {
  id: string;
  name: string;
  stage: DealStage;
  value: number;
  salesforce_id: string;
  close_date?: string;
}
"""
